version: '3'
services:
  tollgate_api:
    image: xturcin0/ads_projekt2:2025
    container_name: tollgate_api
    ports:
      - "8001:8001"
    networks:
      - tollgate_network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - tollgate_network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - tollgate_network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - prometheus

  exporter:
    build:
      context: ./exporter
    container_name: tollgate_exporter
    ports:
      - "8000:8000"  # exporter metrics endpoint
    networks:
      - tollgate_network
    restart: always
    depends_on:
      - tollgate_api

networks:
  tollgate_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: